site_name: "Workshop: Equinix Fabric Cloud Router (FCR) Multi-cloud with Pulumi"

repo_url: https://github.com/equinix-labs/pulumi-equinix-fabric-cloud-router-multicloud-workshop
repo_name: equinix-labs/pulumi-equinix-fabric-cloud-router-multicloud-workshop
edit_uri: blob/main/docs

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md

  - Parts:
      - 1. Setup: parts/part1_setup.md
      - 2. Fabric connection to AWS: parts/part2_fabric_connection_to_aws.md
      - 3. Direct Connect configuration: parts/part3_configuring_direct_connect.md
      - 4. Configuring Direct Connect to AWS VPC: parts/part4_connecting_to_a_vpc.md
      - 5. Configuring BGP in Equinix Fabric: parts/part5_configuring_bgp.md
      - 6. Deploying VM Instances in Both Clouds: parts/part6_deploying_vm_instances.md
      - 7. Configuration and Provisioning: parts/part7_provisioning.md
      - 8. Testing Connectivity between GCP and AWS Instances: parts/part8_testing_interconnection.md

  - Conclusion: parts/conclusion.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    logo: simple/equinixmetal
  favicon: images/favicon.svg

  features:
    - navigation.top
    - search.highlight
    - navigation.footer
    - content.code.copy
    - navigation.expand

extra:
  social:
    - icon: simple/equinixmetal
      link: https://deploy.equinix.com
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/@equinixmetal
    - icon: fontawesome/brands/github
      link: https://github.com/equinix-labs
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@EquinixDevelopers

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.keys
